# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-drivenets"
BBFILE_PATTERN_meta-drivenets = "^${LAYERDIR}/"

LAYERSERIES_COMPAT_meta-drivenets = "nanbield scarthgap"

LAYERDEPENDS_meta-drivenets = " \
    phosphor-layer \
    aspeed-layer \
"
